### ISSUE TITLE
Problem with active route

### ISSUE THREAD

**Issue by lippomano** [creativetimofficial/ct-material-dashboard-pro-angular#207]
In my angular project I need to have these 2 routings:
```
 path: 'tickets'
 path: 'tickets/new'
```
Both paths have to be directly in the sidebar (not submenu or similar) like this:
```
{
  path: '/tickets',
  title: 'sidebar.titles.ticket',
  type: 'link',
  icontype: 'shopping_cart'
}
```

So at the moment when I select one of the routings, I see both selected in the sidebar,
Is it possible to apply the active state at only 1 of the routings without changing path?

![catt](https://user-images.githubusercontent.com/27501745/37649144-3705219c-2c31-11e8-9aea-60196665e693.PNG)

**Comment by lippomano** [comment]
Any news?

**Comment by lippomano** [comment]
@chelaruc yes `tickets` and `tickets/new` are 2 different components.
At the moment I used 2 completely different path `tickets` and `buy`...but if there is a way to solve this without changing my routes is better

**Comment by chelaruc** [comment]
@lippomano the component `tickets/new` is a child of `tickets`?

**Comment by lippomano** [comment]
probably you can solve this using:
`[routerLinkActiveOptions]="{exact: true}"`
