### ISSUE TITLE
Sidemenu: DynamicPath, Collapse Submenu

### ISSUE THREAD

**Issue by elvisgn** [creativetimofficial/ct-material-dashboard-pro-angular#210]
Hi,
I'm trying to auto collapse a sub menu inside the sidemenu. I tried the solution in [#112](https://github.com/creativetimofficial/material-dashboard-pro-angular/issues/112) and [#121](https://github.com/creativetimofficial/material-dashboard-pro-angular/issues/121), but it doesn't work for me.

Also, the dynamic paths don't work in sidemenu.

**Comment by dilipt007** [comment]
Hi there, I understand this issue is closed but is there a way to get the solution as how to implement this ?

**Comment by dilipt007** [comment]
What I am looking for is - I am trying to implement the expand/collapse submenu in the sidebar and the menu items are being rendered dynamically as seen in the creative-tim angular templates. Could you please guide me  in the right direction to get this done ?
