### ISSUE TITLE
Error: Cannot find module 'node-sass'

### ISSUE THREAD

**Issue by basiltap** [creativetimofficial/ct-material-dashboard-pro-angular#244]
Hi, When I first installed the pro version, I got an error: Error: Cannot find module 'node-sass'
I previously installed the free version and worked without any problem.
ERROR in ./node_modules/css-loader?{"sourceMap":false,"import":false}!./node_modules/postcss-loader/lib?{"ident":"postcss","sourceMap":false}!./node_modules/sass-loader/lib/loader.js?{"sourceMap":false,"precision":8,"includePaths":[]}!./node_modules/angular-calendar/scss/angular-calendar.scss
Module build failed: Error: Cannot find module 'node-sass'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
...

**Comment by niesteszeck** [comment]
I had a similar problem after an update (of my Linux distribution). I think
npn rebuild did the trick

__________________________
Enviado desde mi celular
