### ISSUE TITLE
Sidebar responsive not right

### ISSUE THREAD

**Issue by niesteszeck** [creativetimofficial/ct-material-dashboard-pro-angular#251]
When changing the size of the navigator windows in some point the sidebar brakes:

Expected behaviour:
![image](https://user-images.githubusercontent.com/3708962/39815893-db564162-536f-11e8-96ab-d217dd0c2e83.png)

Wrong behaviour:
![image](https://user-images.githubusercontent.com/3708962/39815910-ec243710-536f-11e8-8b07-d82a57765edd.png)

How to reproduce:
 
- In Chrome, inspect the page
- Put inspector (dev tools) on right side
- Resize inspector window so the page get resized

**Comment by niesteszeck** [comment]
On live demo happens the same:
![image](https://user-images.githubusercontent.com/3708962/39816186-e2f953d6-5370-11e8-9440-1be1dae169ac.png)

**Comment by chelaruc** [comment]
@niesteszeck, Sorry for the late response. I couldn't reproduce this error on chrome. Can you tell me if this still appear?

**Comment by niesteszeck** [comment]
I still see it, maybe I'm not updated, when 2.0.3 comes out I will check again. I will let you know. But at least on demo app still happens:
![image](https://user-images.githubusercontent.com/3708962/40991001-708589ea-68c0-11e8-9df6-a028b558aad4.png)
