### ISSUE TITLE
NoUiSlider not showing

### ISSUE THREAD

**Issue by somada141** [creativetimofficial/ct-material-dashboard-pro-angular#255]
Hi there,

I've been trying to get NoUiSlider to work but the result is always something like this:

![image](https://user-images.githubusercontent.com/272419/40152626-3be1bf52-59b0-11e8-868e-85a169f8f9e6.png)

Code:

```
            <form [formGroup]="form2">
              <div class="form-group">
                <nouislider
                  class="slider slider-info form-control"
                  [min]="0"
                  [max]="100"
                  [step]="1"
                  [connect]="true"
                  [tooltips]="true"
                  [formControl]="form2.get('years')"
                ></nouislider>
              </div>
            </form>
```

```
    this.form2 = new FormGroup({
      years: new FormControl([10, 50]),
    });
```

I've imported `"../node_modules/nouislider/distribute/nouislider.min.js"` in `angular-cli.json`, `NouisliderModule` in `AngularLayoutModule` and `@import "plugins/plugin-nouislider";` in `material-dashboard.scss`.

Have I missed something?

**Comment by chelaruc** [comment]
@somada141 have you imported NouisliderModule in your module?

**Comment by somada141** [comment]
@chelaruc I'm importing it as such in the `AdminLayoutModule`:

```
import { NouisliderModule } from 'ng2-nouislider';

@NgModule({
  imports: [
    CommonModule,
    RouterModule.forChild(AdminLayoutRoutes),
    FormsModule,
    ReactiveFormsModule,
    MatButtonModule,
    MatRippleModule,
    MatInputModule,
    MatTooltipModule,
    MatChipsModule,
    MatIconModule,
    MatAutocompleteModule,
    ...
    NouisliderModule,
  ],
  declarations: [
    ...
  ],
  providers: [...]
})

export class AdminLayoutModule {}
```

**Comment by somada141** [comment]
Should I be importing in the `AppModule` instead?

**Comment by chelaruc** [comment]
@somada141 we have imported it in FormsModule, so you need to import you where you are using it.
