### ISSUE TITLE
No mixin named ....

### ISSUE THREAD

**Issue by totalpanic** [creativetimofficial/ct-material-dashboard-pro-angular#265]
Hi,
I am trying to add Material Dashboard PRO Angular - v2.0.2 to an existing Angular+Core2+Identity project.
I have copied assets/scss folder to the exiting project. Made sure package.json has all required packages listed. Referenced material-dashboard.scss in angular-cli.json. 

When I build the project i get following error 

` fail: Microsoft.AspNetCore.SpaServices[0]
      ERROR in ./src/assets/scss/material-dashboard.scss
Module build failed: 
      undefined
                ^
            No mixin named hover

Backtrace:
	src/assets/scss/core/mixins/_buttons.scss:7, in mixin `bmd-button-variant`
	src/assets/scss/core/mixins/_buttons.scss:180, in mixin `bmd-raised-button-variant`
	src/assets/scss/core/mixins/_buttons.scss:214, in mixin `bmd-raised-button-color`
	src/assets/scss/core/_buttons.scss:25
`
Am I missing some step?

Thanks,
GK

**Comment by chelaruc** [comment]
Hi, @totalpanic! Thank you for using our product and sorry for the late response. Have you managed to fix it? Are you sure you have the right scss files? Best, Ciprian

**Comment by totalpanic** [comment]
Yes got it working. Turned out to be outdated packages, even though the
correct versions were specified.

Thanks,
GK
