### ISSUE TITLE
brand-secondary color

### ISSUE THREAD

**Issue by niesteszeck** [creativetimofficial/ct-material-dashboard-pro-angular#268]
Is there any plan to add a brand-secondary color to _brand.scss?

**Comment by chelaruc** [comment]
@niesteszeck why you need brand-secondary?

**Comment by niesteszeck** [comment]
I want to theme my app with 2 main colors, but also use info, warning, and danger

**Comment by chelaruc** [comment]
@niesteszeck you can create your own brand if you want.
