### ISSUE TITLE
Overlay problem in mat-datepicker and mat-select with material v6

### ISSUE THREAD

**Issue by lippomano** [creativetimofficial/ct-material-dashboard-pro-angular#270]
Both datepicker and select have an overlay problem with your CSS.
when you try to select an option from mat-select or a date in mat-datepicker there is an overlay in front of the page and I can't do anything.
The problem probably is here in your CSS:
`
.cdk-overlay-backdrop {
    position: absolute;
    top: 0;
    bottom: 0;
    left: 0;
    right: 0;
    z-index: 1031;
    pointer-events: auto;
    -webkit-tap-highlight-color: transparent;
    transition: opacity 400ms cubic-bezier(0.25, 0.8, 0.25, 1);
    opacity: 0;
}
`

z-index is too high and it covers other things

**Comment by chelaruc** [comment]
@lippomano Can you tell me the steps to reproduce that?

**Comment by lippomano** [comment]
Just try to use [mat-datepicker](https://material.angular.io/components/datepicker/overview) or [select](https://material.angular.io/components/select/overview)

**Comment by buildYourNet** [comment]
What solved the problem for me was that in the scss _plugin-datetime-picker.scss I reduced the z-index to 1000 of  .cdk-global-overlay-wrapper.

**Comment by Avadhesh-Patel** [comment]
I am also facing same issue for mat-select. Please check attached image for more information.

![image](https://user-images.githubusercontent.com/16130486/43827876-96f09f54-9b18-11e8-8d6b-7fbfa60a1e5a.png)

**Comment by buildYourNet** [comment]
@Avadhesh-Patel try to change .cdk-global-overlay-wrapper. and .cdk-overlay-wrapper to 1000 in the  _plugin-datetime-picker.scss file. You can find it in the \src\assets\scss\plugins folder

**Comment by Avadhesh-Patel** [comment]
@buildYourNet Thanks man.. It's working now ...
