### ISSUE TITLE
Theme mat-expansion-panel

### ISSUE THREAD

**Issue by niesteszeck** [creativetimofficial/ct-material-dashboard-pro-angular#275]
Hi, I would like to use `mat-expansion-panel`, but isn't themed. As is square and with a dark border it looks strange on the theme. I want to use something like a `box-shadow: 0 1px 4px 0 rgba(0,0,0,.14);` to it, using the above patch.

```diff
Index: src/assets/scss/core/_forms.scss
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- src/assets/scss/core/_forms.scss	(revision 5489b6ba80b4f5bd06fd5447ef8570d4123c8173)
+++ src/assets/scss/core/_forms.scss	(date 1529590595000)
@@ -376,6 +376,10 @@
   }
 }
 
+.mat-expansion-panel {
+  box-shadow: 0 1px 4px 0 rgba(0,0,0,.14);
+}
+
 .mat-form-field {
   display: block !important;
 }

```
The problem is that gets overriden by:
```css
.mat-expansion-panel:not([class*=mat-elevation-z])
``` 
Any suggestion?

How it looks with the patch overriden
![image](https://user-images.githubusercontent.com/3708962/41725700-77358bca-753e-11e8-8fc7-2a7ee9f68c61.png)

How it looks if I disable `.mat-expansion-panel:not([class*=mat-elevation-z])`
![image](https://user-images.githubusercontent.com/3708962/41728400-c24836ca-7544-11e8-8b03-761151a24477.png)

**Comment by chelaruc** [comment]
@niesteszeck I think with `box-shadow: 0 1px 4px 0 rgba(0,0,0,.14);` is looking more better and you can override it with !important.

**Comment by niesteszeck** [comment]
Thks, it works like a charm. New Patch:
```diff
Index: src/assets/scss/core/_forms.scss
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- src/assets/scss/core/_forms.scss	(revision 5489b6ba80b4f5bd06fd5447ef8570d4123c8173)
+++ src/assets/scss/core/_forms.scss	(date 1529590595000)
@@ -376,6 +376,10 @@
   }
 }
 
+.mat-expansion-panel {
+  box-shadow: 0 1px 4px 0 rgba(0,0,0,.14) !important;
+}
+
 .mat-form-field {
   display: block !important;
 }

```
