### ISSUE TITLE
ng build --prod --base-href "./" is not loading the scss and js correctly

### ISSUE THREAD

**Issue by oneal1801** [creativetimofficial/ct-material-dashboard-pro-angular#282]
Hello @timcreative , @chelaruc 

i am having issues anytime i run the ng build --prod --base-href "./", When i open the dist/index.html file that is generate it wont load the page, it will show just a white screen, the only thing that is display is the favicon and the title of the page, nothing else. 

    "@agm/core": "1.0.0-beta.2",
    "@angular/animations": "6.0.2",
    "@angular/cdk": "6.1.0",
    "@angular/common": "6.0.2",
    "@angular/compiler": "6.0.2",
    "@angular/core": "6.0.2",
    "@angular/forms": "6.0.2",
    "@angular/http": "6.0.2",
    "@angular/material": "6.1.0",
    "@angular/platform-browser": "6.0.2",
    "@angular/platform-browser-dynamic": "6.0.2",
    "@angular/platform-server": "6.0.2",
    "@angular/router": "6.0.2",
    
    "angular-calendar": "0.23.1",

    "@angular-devkit/build-angular": "0.6.3",
    "@angular/cli": "6.0.8",
    "@angular/compiler-cli": "6.0.2",

**Comment by 7carlosz** [comment]
solution?

**Comment by chelaruc** [comment]
@oneal1801 have you tried the solution from @7carlosz? Best, Ciprian
