### ISSUE TITLE
Register page background image not covering full page in Firefox

### ISSUE THREAD

**Issue by zbalda** [creativetimofficial/ct-material-dashboard-pro-angular#283]
In Firefox on my local host and on the Creative Tim live preview the background image of the register page does not cover the entire page. On the login page the background image covers it just fine. Not sure why the background image is working on the login page but not on the register page.

![screenshot_2018-07-07](https://user-images.githubusercontent.com/22688955/42416024-ae881f66-8231-11e8-8e3c-02420ca93d0d.png)

In Chrome, the background image covers the entire register page, but the register card shows up awkwardly low on the screen.

**Comment by zbalda** [comment]
Also I'm using v2.1.0 with BS4

**Comment by chelaruc** [comment]
@zbalda thank you for using our product and sorry for the late response. Change the `min-height to 100vh` in `.page-header`. 

Best, Ciprian
