### ISSUE TITLE
Calendar integration

### ISSUE THREAD

**Issue by USTSweb** [creativetimofficial/ct-material-dashboard-pro-angular#287]
Hello,
I'm a dev from USTS and i work on your template. I have some question about some component which i don't implemente successfully or tips for some features.
My first question will be on the calendar. Can i implement it in a card juste with the tag <app-calendar-cmp> or need i to adapte it with some sccs and ts on my component. When i put it on my page, it take all the place and it's on the first plan. 
The second one will be about make appears a dropdown when the user click on a row of the table. 
In the template give by the designer, i need to change the background of the side bar but i can't find where you set the color of it. I know we can change it dynamically by the plugin. 
Thanx you for your help.

**Comment by chelaruc** [comment]
@USTSweb, I have responded to you on email. Best, Ciprian
