### ISSUE TITLE
Freaky shakiness hovering country boundaries

### ISSUE THREAD

**Issue by ezebc182** [creativetimofficial/ct-material-dashboard-pro-angular#289]
![crash-material-admin-pro](https://user-images.githubusercontent.com/5577862/43678661-c46ec632-97ed-11e8-9a93-f9daa0611df0.gif)

If you hover countries, you will notice the shakiness. Even the gif couldn't show the real behavior because is much faster than the gif captured.

**Comment by F0rt1s** [comment]
Same here.

**Comment by chelaruc** [comment]
@F0rt1s @ezebc182 what browser do you use? Best, Ciprian

**Comment by ezebc182** [comment]
@chelaruc I apologize for my delayed response. The version was Chrome Versión 69.0.3497.100 (Build oficial) (64 bits)

**Comment by chelaruc** [comment]
@ezebc182 what version do you have? The last one is 2.1.1.

**Comment by ezebc182** [comment]
@chelaruc I faced this in your [live demo](https://demos.creative-tim.com/material-dashboard-pro-angular2/dashboard?_ga=2.165700222.1103681989.1539742477-333155407.1507170282)

**Comment by chelaruc** [comment]
@ezebc182 and what OS?

**Comment by ezebc182** [comment]
@chelaruc both Windows 10 64-bit and Ubuntu 18.04.1 LTS
