### ISSUE TITLE
Wrong animation in dropdown

### ISSUE THREAD

**Issue by lippomano** [creativetimofficial/ct-material-dashboard-pro-angular#291]
I have a strange animation with the dropdown
![ezgif com-crop](https://user-images.githubusercontent.com/27501745/43829193-a59b5a68-9afe-11e8-8b4c-acd56112e73c.gif)
Like you see in the GIF the panel seems to come down and it is not the correct animation.
I am using it in a test project to see what is the cause of it, and this is the current angular.json:
![cattura](https://user-images.githubusercontent.com/27501745/43829376-09650ca6-9aff-11e8-8243-0a91fa10941c.JPG)

If I remove your scss and just add my styles.scss (in styles.scss there is only the bootstrap css import `@import "~bootstrap/dist/css/bootstrap.css";` ) I have the correct behaviour:
![ezgif com-crop22](https://user-images.githubusercontent.com/27501745/43829626-ab73de50-9aff-11e8-83bb-95975e29e437.gif)

And this is the angular.json
![cattura22](https://user-images.githubusercontent.com/27501745/43829673-c9451b92-9aff-11e8-95cc-c19f87977feb.JPG)

Any idea how to fix this problem?

**Comment by lippomano** [comment]
This is the example:
https://drive.google.com/open?id=1-nnp_Rj3q4M989N-1WsarxJ2VMOTrsCL

**Comment by chelaruc** [comment]
@lippomano sorry for the late response. What version do you have?

**Comment by lippomano** [comment]
@chelaruc version 2.1.0

**Comment by chelaruc** [comment]
@lippomano can you give me an example with this behavior in our product?

**Comment by lippomano** [comment]
It was an import problem, you can close.
