### ISSUE TITLE
Login page button "Lets go" not clickable on different zoom

### ISSUE THREAD

**Issue by cdorde** [creativetimofficial/ct-material-dashboard-pro-angular#293]
Steps to produce error:
1. Open demo site on desktop chrome (https://demos.creative-tim.com/material-dashboard-pro-angular2/dashboard?_ga=2.115971142.1353545506.1527279521-1965686447.1526913373)
2. Click "Pages"
3. Click "Login"
4. Change zoom to 125%
5. Try to click on button "LETS GO"

Expected behaviour: Button is clickable.

Temporaty solution: change zoom to lower value.

Please, can you fix this issue. Same problem exists with firefox and safari.

Can you add me to your private git? I bought personal licence of this theme. My github user name is cdorde@gmail.com

Best regards,

Đorđe

**Comment by chelaruc** [comment]
@cdorde all you have to do is to go in `src/assets/scss/core/_headers.scss` and change the line 59 `z-index: 2;` with`z-index: 3;` and after line 61 add:
```
.footer .container{
        z-index: 2;
    }
```

All the best,
Ciprian
