### ISSUE TITLE
Is there any better ways to fill data rather than setTimeout?

### ISSUE THREAD

**Issue by baonbt** [creativetimofficial/ct-material-dashboard-pro-angular#294]
Hi, I got a problem with datatable, I think setTimeout is not a good idea. When you refresh the table so quick (shorter than Timeout interval), you will got an err (datatable cannot reinitialise datatable). If Timeout too short, your table will not be loaded completely(low network connection).
I tried to load data by ajax, `$('#datatables').DataTable({ajax:"jsondata"})`  but ngFor or repeat cannot work with this case. Then I cannot add button with MD Pro custom style into the table.
Could anyone give me a suggestion? Thanks you alot.

**Comment by dupiesdupreez** [comment]
I have Exactly the same problem. 

My timeout is at 0 seconds. But like you said, might have problems when the network is slow.

**Comment by niesteszeck** [comment]
maybe on #33 you can found some other approach. I use services to load data asyncroniusly from server side and put it into a datatable with ngFor, see [this](https://github.com/creativetimofficial/ct-material-dashboard-pro-angular/issues/33#issuecomment-347873630)
