### ISSUE TITLE
mat-selection-list is not displaying un-selected checkbox

### ISSUE THREAD

**Issue by Avadhesh-Patel** [creativetimofficial/ct-material-dashboard-pro-angular#298]
Hi,
For this input
<mat-selection-list>
                <mat-list-option>
                    1
                </mat-list-option>
                <mat-list-option>
                    2
                </mat-list-option>
                <mat-list-option>
                    3
                </mat-list-option>
</mat-selection-list>

we are getting following output.

![image](https://user-images.githubusercontent.com/16130486/46058854-4d309300-c17a-11e8-874d-5fec8e077afb.png)

**Comment by chelaruc** [comment]
@Avadhesh-Patel how can I help you?

**Comment by Avadhesh-Patel** [comment]
Empty check box is not showing on html ... mat-selection-list.. only selected one displayed ...

**Comment by chelaruc** [comment]
@Avadhesh-Patel can you give me some example code for testing?

**Comment by Avadhesh-Patel** [comment]
Empty check box is not showing on html ... mat-selection-list.. only selected one displayed ...

Try following code in **material-dashboard-pro-angular**  code base.

<mat-selection-list>
  <mat-list-option>    a  </mat-list-option>
  <mat-list-option>    b  </mat-list-option>
  <mat-list-option>    c  </mat-list-option>
</mat-selection-list>

**Comment by Avadhesh-Patel** [comment]
Empty check box is not showing on html ... mat-selection-list.. only selected one displayed ...

Try following code in material-dashboard-pro-angular code base.

[code.txt](https://github.com/creativetimofficial/ct-material-dashboard-pro-angular/files/2510000/code.txt)

**Comment by Avadhesh-Patel** [comment]
It's working now as per your guidance.  
Thanks .. Ciprian @chelaruc
