### ISSUE TITLE
Update dependencies for bootstrap-tagsinput

### ISSUE THREAD

**Issue by Cynicszm** [creativetimofficial/ct-material-dashboard-pro-angular#312]
# Current Behavior

One of the dependencies in package.json is listed as bootstrap-tagsinput@0.7.1. This version is old and not actively maintained and will cause npm audit to fail with a high severity cross-site scripting error https://www.npmjs.com/advisories/124

Please can this be updated to use an actively maintained version

**Comment by chelaruc** [comment]
@Cynicszm you can remove it from package.json file and from angular.json file. We are not using it. We will clean our product too.
