### ISSUE TITLE
How to use Calender

### ISSUE THREAD

**Issue by luizbsilva** [creativetimofficial/ct-material-dashboard-pro-angular#315]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x ] I am running the latest version
- [x ] I checked the documentation and found no answer
- [x ] I checked to make sure that this issue has not already been filed
- [x ] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Dynamic data loads in the calendar component

# Current Behavior

I can not load the dynamic data in the calendar component only data prefixed in ngOnInit

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.
I would like a help with an example of loading data from an eternal api;

**Comment by chelaruc** [comment]
@luizbsilva check this link: [https://stackoverflow.com/questions/27920314/fullcalendar-add-events-dynamically](https://stackoverflow.com/questions/27920314/fullcalendar-add-events-dynamically)

**Comment by luizbsilva** [comment]
thank you

Em seg, 11 de fev de 2019 às 11:53, Chelaru Ciprian <
notifications@github.com> escreveu:
