### ISSUE TITLE
Problem with Build 

### ISSUE THREAD

**Issue by ShabnamPaidarfard** [creativetimofficial/ct-material-dashboard-pro-angular#321]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Please describe the behavior you are expecting

# Current Behavior

What is the current behavior?

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device:
* Operating System:
* Browser and Version:

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by ShabnamPaidarfard** [comment]
I get this failure when trying to build and deploy.


[0m[1m[31mERROR in ./node_modules/angular-calendar/scss/angular-calendar.scss (./node_modules/raw-loader!./node_modules/postcss-loader/lib??embedded!./node_modules/sass-loader/lib/loader.js??ref--14-3!./node_modules/angular-calendar/scss/angular-calendar.scss)[39m[22m[0m
[0m[1m[31mModule build failed: Error: Cannot find module 'node-sass'[39m[22m[0m
[0m[1m[31m    at Function.Module._resolveFilename (module.js:555:15)[39m[22m[0m
[0m[1m[31m    at Function.Module._load (module.js:482:25)[39m[22m[0m
[0m[1m[31m    at Module.require (module.js:604:17)[39m[22m[0m
[0m[1m[31m    at require (internal/module.js:11:18)[39m[22m[0m
[0m[1m[31m    at Object.sassLoader (/tmp/styleguide-argon-dashboard/node_modules/sass-loader/lib/loader.js:46:72)[39m[22m[0m
[0m[1m[31mERROR in ./src/assets/scss/material-dashboard.scss (./node_modules/raw-loader!./node_modules/postcss-loader/lib??embedded!./node_modules/sass-loader/lib/loader.js??ref--14-3!./src/assets/scss/material-dashboard.scss)[39m[22m[0m
[0m[1m[31mModule build failed: Error: Cannot find module 'node-sass'[39m[22m[0m
[0m[1m[31m    at Function.Module._resolveFilename (module.js:555:15)[39m[22m[0m
[0m[1m[31m    at Function.Module._load (module.js:482:25)[39m[22m[0m
[0m[1m[31m    at Module.require (module.js:604:17)[39m[22m[0m
[0m[1m[31m    at require (internal/module.js:11:18)[39m[22m[0m
[0m[1m[31m    at Object.sassLoader (/tmp/styleguide-argon-dashboard/node_modules/sass-loader/lib/loader.js:46:72)[39m[22m[0m
[0m[1m[31mERROR in ./node_modules/sweetalert2/src/sweetalert2.scss (./node_modules/raw-loader!./node_modules/postcss-loader/lib??embedded!./node_modules/sass-loader/lib/loader.js??ref--14-3!./node_modules/sweetalert2/src/sweetalert2.scss)[39m[22m[0m
[0m[1m[31mModule build failed: Error: Cannot find module 'node-sass'[39m[22m[0m
[0m[1m[31m    at Function.Module._resolveFilename (module.js:555:15)[39m[22m[0m
[0m[1m[31m    at Function.Module._load (module.js:482:25)[39m[22m[0m
[0m[1m[31m    at Module.require (module.js:604:17)[39m[22m[0m
[0m[1m[31m    at require (internal/module.js:11:18)[39m[22m[0m
[0m[1m[31m    at Object.sassLoader (/tmp/styleguide-argon-dashboard/node_modules/sass-loader/lib/loader.js:46:72)[39m[22m[0m
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! material-dashboard-pro-angular@2.2.0 build: `ng build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the material-dashboard-pro-angular@2.2.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/app/.npm/_logs/2019-05-15T18_51_30_476Z-debug.log
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
ERROR: script returned exit code 1
Finished: FAILURE

**Comment by chelaruc** [comment]
@ShabnamPaidarfard  try this command: npm rebuild node-sass --force
