### ISSUE TITLE
ng serve

### ISSUE THREAD

**Issue by ShabnamPaidarfard** [creativetimofficial/ct-material-dashboard-pro-angular#323]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Please describe the behavior you are expecting

# Current Behavior

What is the current behavior?

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device:
* Operating System:
* Browser and Version:

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by ShabnamPaidarfard** [comment]
when I run ng serve this the error I get

ERROR in ./src/assets/scss/material-dashboard.scss (./node_modules/raw-loader!./node_modules/postcss-loader/lib??embedded!./node_modules/sass-loader/lib/loader.js??ref--14-3!./src/assets/scss/material-dashboard.scss)
Module build failed: Error: Cannot find module 'node-sass'
Require stack:
- /Users/shabnam.paidarfard/repo/styleguide-argon-dashboard/node_modules/sass-loader/lib/loader.js
- /Users/shabnam.paidarfard/repo/styleguide-argon-dashboard/node_modules/loader-runner/lib/loadLoader.js
- /Users/shabnam.paidarfard/repo/styleguide-argon-dashboard/node_modules/loader-runner/lib/LoaderRunner.js
- /Users/shabnam.paidarfard/repo/styleguide-argon-dashboard/node_modules/webpack/lib/NormalModule.js
- /Users/shabnam.paidarfard/repo/styleguide-argon-dashboard/node_modules/webpack/lib/NormalModuleFactory.js
- /Users/shabnam.paidarfard/repo/styleguide-argon-dashboard/node_modules/webpack/lib/Compiler.js
- /Users/shabnam.paidarfard/repo/styleguide-argon-dashboard/node_modules/webpack/lib/webpack.js
- /Users/shabnam.paidarfard/repo/styleguide-argon-dashboard/node_modules/@angular-devkit/build-angular/src/dev-server/index.js
- /Users/shabnam.paidarfard/repo/styleguide-argon-dashboard/node_modules/@angular/cli/node_modules/@angular-devkit/architect/src/architect.js
- /Users/shabnam.paidarfard/repo/styleguide-argon-dashboard/node_modules/@angular/cli/node_modules/@angular-devkit/architect/src/index.js
- /Users/shabnam.paidarfard/repo/styleguide-argon-dashboard/node_modules/@angular/cli/models/architect-command.js
- /Users/shabnam.paidarfard/repo/styleguide-argon-dashboard/node_modules/@angular/cli/commands/build-impl.js
- /Users/shabnam.paidarfard/repo/styleguide-argon-dashboard/node_modules/@angular/cli/node_modules/@angular-devkit/schematics/tools/export-ref.js
- /Users/shabnam.paidarfard/repo/styleguide-argon-dashboard/node_modules/@angular/cli/node_modules/@angular-devkit/schematics/tools/index.js
- /Users/shabnam.paidarfard/repo/styleguide-argon-dashboard/node_modules/@angular/cli/utilities/json-schema.js
- /Users/shabnam.paidarfard/repo/styleguide-argon-dashboard/node_modules/@angular/cli/models/command-runner.js
- /Users/shabnam.paidarfard/repo/styleguide-argon-dashboard/node_modules/@angular/cli/lib/cli/index.js
- /Users/shabnam.paidarfard/repo/styleguide-argon-dashboard/node_modules/@angular/cli/lib/init.js
- /Users/shabnam.paidarfard/repo/styleguide-argon-dashboard/node_modules/@angular/cli/bin/ng
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:610:15)
    at Function.Module._load (internal/modules/cjs/loader.js:526:27)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.sassLoader (/Users/shabnam.paidarfard/repo/styleguide-argon-dashboard/node_modules/sass-loader/lib/loader.js:46:72)
ERROR in ./node_modules/angular-calendar/scss/angular-calendar.scss (./node_modules/raw-loader!./node_modules/postcss-loader/lib??embedded!./node_modules/sass-loader/lib/loader.js??ref--14-3!./node_modules/angular-calendar/scss/angular-calendar.scss)
Module build failed: Error: Cannot find module 'node-sass'
Require stack:
- /Users/shabnam.paidarfard/repo/styleguide-argon-dashboard/node_modules/sass-loader/lib/loader.js
- /Users/shabnam.paidarfard/repo/styleguide-argon-dashboard/node_modules/loader-runner/lib/loadLoader.js
- /Users/shabnam.paidarfard/repo/styleguide-argon-dashboard/node_modules/loader-runner/lib/LoaderRunner.js
- /Users/shabnam.paidarfard/repo/styleguide-argon-dashboard/node_modules/webpack/lib/NormalModule.js
- /Users/shabnam.paidarfard/repo/styleguide-argon-dashboard/node_modules/webpack/lib/NormalModuleFactory.js
- /Users/shabnam.paidarfard/repo/styleguide-argon-dashboard/node_modules/webpack/lib/Compiler.js
- /Users/shabnam.paidarfard/repo/styleguide-argon-dashboard/node_modules/webpack/lib/webpack.js
- /Users/shabnam.paidarfard/repo/styleguide-argon-dashboard/node_modules/@angular-devkit/build-angular/src/dev-server/index.js
- /Users/shabnam.paidarfard/repo/styleguide-argon-dashboard/node_modules/@angular/cli/node_modules/@angular-devkit/architect/src/architect.js
- /Users/shabnam.paidarfard/repo/styleguide-argon-dashboard/node_modules/@angular/cli/node_modules/@angular-devkit/architect/src/index.js
- /Users/shabnam.paidarfard/repo/styleguide-argon-dashboard/node_modules/@angular/cli/models/architect-command.js
- /Users/shabnam.paidarfard/repo/styleguide-argon-dashboard/node_modules/@angular/cli/commands/build-impl.js
- /Users/shabnam.paidarfard/repo/styleguide-argon-dashboard/node_modules/@angular/cli/node_modules/@angular-devkit/schematics/tools/export-ref.js
- /Users/shabnam.paidarfard/repo/styleguide-argon-dashboard/node_modules/@angular/cli/node_modules/@angular-devkit/schematics/tools/index.js
- /Users/shabnam.paidarfard/repo/styleguide-argon-dashboard/node_modules/@angular/cli/utilities/json-schema.js
- /Users/shabnam.paidarfard/repo/styleguide-argon-dashboard/node_modules/@angular/cli/models/command-runner.js
- /Users/shabnam.paidarfard/repo/styleguide-argon-dashboard/node_modules/@angular/cli/lib/cli/index.js
- /Users/shabnam.paidarfard/repo/styleguide-argon-dashboard/node_modules/@angular/cli/lib/init.js
- /Users/shabnam.paidarfard/repo/styleguide-argon-dashboard/node_modules/@angular/cli/bin/ng
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:610:15)
    at Function.Module._load (internal/modules/cjs/loader.js:526:27)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.sassLoader (/Users/shabnam.paidarfard/repo/styleguide-argon-dashboard/node_modules/sass-loader/lib/loader.js:46:72)
ERROR in ./node_modules/sweetalert2/src/sweetalert2.scss (./node_modules/raw-loader!./node_modules/postcss-loader/lib??embedded!./node_modules/sass-loader/lib/loader.js??ref--14-3!./node_modules/sweetalert2/src/sweetalert2.scss)
Module build failed: Error: Cannot find module 'node-sass'
Require stack:
- /Users/shabnam.paidarfard/repo/styleguide-argon-dashboard/node_modules/sass-loader/lib/loader.js
- /Users/shabnam.paidarfard/repo/styleguide-argon-dashboard/node_modules/loader-runner/lib/loadLoader.js
- /Users/shabnam.paidarfard/repo/styleguide-argon-dashboard/node_modules/loader-runner/lib/LoaderRunner.js
- /Users/shabnam.paidarfard/repo/styleguide-argon-dashboard/node_modules/webpack/lib/NormalModule.js
- /Users/shabnam.paidarfard/repo/styleguide-argon-dashboard/node_modules/webpack/lib/NormalModuleFactory.js
- /Users/shabnam.paidarfard/repo/styleguide-argon-dashboard/node_modules/webpack/lib/Compiler.js
- /Users/shabnam.paidarfard/repo/styleguide-argon-dashboard/node_modules/webpack/lib/webpack.js
- /Users/shabnam.paidarfard/repo/styleguide-argon-dashboard/node_modules/@angular-devkit/build-angular/src/dev-server/index.js
- /Users/shabnam.paidarfard/repo/styleguide-argon-dashboard/node_modules/@angular/cli/node_modules/@angular-devkit/architect/src/architect.js
- /Users/shabnam.paidarfard/repo/styleguide-argon-dashboard/node_modules/@angular/cli/node_modules/@angular-devkit/architect/src/index.js
- /Users/shabnam.paidarfard/repo/styleguide-argon-dashboard/node_modules/@angular/cli/models/architect-command.js
- /Users/shabnam.paidarfard/repo/styleguide-argon-dashboard/node_modules/@angular/cli/commands/build-impl.js
- /Users/shabnam.paidarfard/repo/styleguide-argon-dashboard/node_modules/@angular/cli/node_modules/@angular-devkit/schematics/tools/export-ref.js
- /Users/shabnam.paidarfard/repo/styleguide-argon-dashboard/node_modules/@angular/cli/node_modules/@angular-devkit/schematics/tools/index.js
- /Users/shabnam.paidarfard/repo/styleguide-argon-dashboard/node_modules/@angular/cli/utilities/json-schema.js
- /Users/shabnam.paidarfard/repo/styleguide-argon-dashboard/node_modules/@angular/cli/models/command-runner.js
- /Users/shabnam.paidarfard/repo/styleguide-argon-dashboard/node_modules/@angular/cli/lib/cli/index.js
- /Users/shabnam.paidarfard/repo/styleguide-argon-dashboard/node_modules/@angular/cli/lib/init.js
- /Users/shabnam.paidarfard/repo/styleguide-argon-dashboard/node_modules/@angular/cli/bin/ng
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:610:15)
    at Function.Module._load (internal/modules/cjs/loader.js:526:27)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.sassLoader (/Users/shabnam.paidarfard/repo/styleguide-argon-dashboard/node_modules/sass-loader/lib/loader.js:46:72)
ℹ ｢wdm｣: Failed to compile.

**Comment by chelaruc** [comment]
#321
