### ISSUE TITLE
How to resove access issue for fonts.googleapi.com in China

### ISSUE THREAD

**Issue by zhq3k** [creativetimofficial/ct-material-dashboard-pro-angular#326]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ yes] I am running the latest version
- [ yes] I checked the documentation and found no answer
- [ yes] I checked to make sure that this issue has not already been filed
- [ yes] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Have another solution to access googleapi fonts in China?
and could you pack the fonts to your css files?

# Current Behavior

As you known, Cannot access it in China

**Comment by chelaruc** [comment]
Hi, @zhq3k. Thank you for using our product. We didn't know that. I found a solution here: https://www.hongkiat.com/blog/google-fonts-china/
