### ISSUE TITLE
Retun login class nav-open in body

### ISSUE THREAD

**Issue by ghten** [creativetimofficial/ct-material-dashboard-pro-angular#329]
In phone, when I do a logout, I return to page login and body has the class nav-open. If I reload, the body is normal, at the start, it's normal too.

thanks

**Comment by chelaruc** [comment]
@ghten Thank you for using our product. 
Have you deleted this code from auth.component.ts?
```
this._router = this.router.events.filter(event => event instanceof NavigationEnd).subscribe((event: NavigationEnd) => {
      this.sidebarClose();
      const $layer = document.getElementsByClassName('close-layer')[0];
      if ($layer) {
        $layer.remove();
      }
    });
```
And also, why you didn't used our ISSUE_TEMPLATE?
