### ISSUE TITLE
Fixed navbar still not working follow documentation

### ISSUE THREAD

**Issue by lubo08** [creativetimofficial/ct-material-dashboard-pro-angular#331]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ x] I am running the latest version
- [x ] I checked the documentation and found no answer
- [x ] I checked to make sure that this issue has not already been filed
- [ x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Navbar Fixed: please go app/layouts/admin/admin-layout.component.html and move the <navbar-cmp></navbar-cmp> outside of div with class .main-panel. Then go to app/shared/navbar/navbar.component.html and add the class .navbar-dashboard-fixed.

# Current Behavior

Not work at all.

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

just flow instructions in documentation

Navbar Fixed: please go app/layouts/admin/admin-layout.component.html and move the <navbar-cmp></navbar-cmp> outside of div with class .main-panel. Then go to app/shared/navbar/navbar.component.html and add the class .navbar-dashboard-fixed.

**Comment by chelaruc** [comment]
@lubo08 thank you for using our product. We'll update the documentation in the next update. For now, all you have to do is to add the class `fixed-top` to the navbar and in the `src/assets/scss/dashboard/_navbar.scss` file change the `.fixed-top` class with:
``` 
&.fixed-top{
    position: fixed !important;
    width: calc(100% - 260px);
    right: 0;
    left: auto;
  }
```
