### ISSUE TITLE
[Feature Request] Json data

### ISSUE THREAD

**Issue by MutisoKelv** [creativetimofficial/ct-material-dashboard-pro-angular#336]
### What is your enhancement?
How do I call json data and display it here on the chartist charts?

**Comment by chelaruc** [comment]
@MutisoKelv thank you for using our product. You need to convert you json data to match the chartist options.

**Comment by MutisoKelv** [comment]
Please show me how... My client is almost swallowing me alive 😂

**Comment by MutisoKelv** [comment]
@chelaruc

**Comment by chelaruc** [comment]
@MutisoKelv check this pen: https://codepen.io/k3no/pen/NRVgbo?editors=0010

**Comment by chelaruc** [comment]
Here you have another tutorial: https://egghead.io/lessons/angular-fetch-data-from-an-api-using-the-httpclient-in-angular

**Comment by MutisoKelv** [comment]
Thank you.
