### ISSUE TITLE
Wizard

### ISSUE THREAD

**Issue by ryoma76** [creativetimofficial/ct-material-dashboard-pro-angular#337]
good morning,
inside the form wizard when I insert a input select the validation does not work, and inside the form the select field is not visible

**Comment by chelaruc** [comment]
@ryoma76 thank you for using our product. Please use the Issue Template.

**Comment by ryoma76** [comment]
> @ryoma76 thank you for using our product. Please use the Issue Template.

sorry
Material Dashboard Pro Angular
