### ISSUE TITLE
How can i change sidebar color?

### ISSUE THREAD

**Issue by therentalguys** [creativetimofficial/ct-material-dashboard-pro-angular#340]
Version 2.3.0

**Comment by chelaruc** [comment]
Hi @therentalguys. Thank you for using our product. You need to change the data-background-color attribute from the `src/app/layouts/admin/admin-layout.component.html` file.

**Comment by therentalguys** [comment]
Thankyou for your reply, i did try that, but i only can choose 3 colors over there, what if i wanted to add purple to it?
