### ISSUE TITLE
How can i change sidebar color? other then Red, white and black

### ISSUE THREAD

**Issue by therentalguys** [creativetimofficial/ct-material-dashboard-pro-angular#341]
Version 2.3.0

**Comment by chelaruc** [comment]
@therentalguys why you haven't used our Issue Template? To change the color, go in `src/assets/scss/dashboard/_sidebar-and-main-panel.scss` and search for data-background-color. There you need to create your own color.

**Comment by renatoredes** [comment]
How can i change sidebar color? other then Red, white and black ????
