### ISSUE TITLE
Modal components doesn't work

### ISSUE THREAD

**Issue by UXruben** [creativetimofficial/ct-material-dashboard-pro-angular#342]
I tried using modals components, but it doesn't work.

https://demos.creative-tim.com/material-dashboard-pro-angular2/#/components/notifications

**Comment by chelaruc** [comment]
Hello there, @UXruben 

Thank you for your interest in working with our products.
It seems that you haven't respected our ISSUE_TEMPLATE, so we are going to close it.
Please add a new comment here, or open a new issue, by filling the mentioned ISSUE_TEMPLATE and please be sure that your issue title is a very small description of your issue as well.

All the best,
Ciprian
Developer @ [Creative-Tim](https://creative-tim.com/)

**Comment by accuit** [comment]
@chelaruc  even if @UXruben does not qualify for issue template. But I can clearly see that you guyz does not care about fixing the issues with your so called perfect templates. There are still many issues on live demo templates.
1. Modal Not opening
2. Sidebar menu toggle not wokinf as expected.
3. Timepicker is not available in template but available in bootstrap template.

Its been many days I have been foloowing the demo but still no progress on issues.
