### ISSUE TITLE
Page styling is not working

### ISSUE THREAD

**Issue by wafi543** [creativetimofficial/ct-material-dashboard-pro-angular#345]
<img width="1280" alt="problem1" src="https://user-images.githubusercontent.com/41089137/67228715-894c2b00-f442-11e9-974a-6ef359726391.png">

When I run "ng serve --open" on template it's working fine, but when I moving all the necessary files to my project; the page looks like in picture above.

I have moved all the files in the folder "app" to my project, also moved "assets" to my project,
and typed the 'import' modules into "app.module.ts".
Did I miss something that I should do?

I want Login Page to be in <app-root> to test it, so I just typed <app-login-cmp></app-login-cmp> in my "app.component.html"

<img width="1280" alt="picure2" src="https://user-images.githubusercontent.com/41089137/67228983-0d061780-f443-11e9-8458-3b07b9fd7f53.png">

**Comment by wafi543** [comment]
I want Login Page to be in the "app-root" to test it, so I just typed the tag "app-login-cmp" in my "app.component.html"

**Comment by chelaruc** [comment]
Hi, @wafi543. Thank you for using our product. Have you imported our styles from the angular.json file?

**Comment by wafi543** [comment]
I have typed all styles and scripts in angular.json as in the picture below, also imported "dependencies" and "devDependencies" to package.json and do the "npm install"

<img width="1680" alt="image1" src="https://user-images.githubusercontent.com/41089137/67272567-7890c900-f4c5-11e9-9930-2e173d2672fd.png">

Then when I refresh the page I get error in console as the picture below:

"Uncaught Error: Can't resolve all parameters for NavbarComponent: (?, ?, ?, ?)."
<img width="1280" alt="image2" src="https://user-images.githubusercontent.com/41089137/67272636-9827f180-f4c5-11e9-9ed1-0ae81e96f98a.png">


The deadline is soon, I have to submit the project by the end of the week. I hope you reply as fast as possible.

**Comment by chelaruc** [comment]
Hi @wafi543,

Unfortunately, we can't help you with the customization of our product. If you have issue with our products, you can contact us. 
If you want the login page to load first, you need to go in the app.routing.ts file and change the redirect to match: pages/login

All the best,
Ciprian
