### ISSUE TITLE
[Bug] Material Dashboard Pro Angular - not working on Internet Explorer nor Microsoft Edge

### ISSUE THREAD

**Issue by ionutafloarei** [creativetimofficial/ct-material-dashboard-pro-angular#350]
### Version
2.3.0
### Reproduction link
https://demos.creative-tim.com/material-dashboard-pro-angular2/#/forms/regular
### Operating System
Windows 10
### Device
Laptop Lenovo
### Browser & Version
IE 11.914 Edge 44.17763
### Steps to reproduce
1. open the link in Internet Explorer and Edge https://demos.creative-tim.com/material-dashboard-pro-angular2/#/forms/regular
2. open the menu in the left and notice that most of the menu elements are not visible anymore
3. open F12 developer tools, console messages and in Edge you have this error:
"SCRIPT1028: SCRIPT1028: Expected identifier, string or number scripts.js (13213,9215)"
4. open F12 developer tools, console messages and in Internet Explorer you have these errors:
ERROR ReferenceError: '$' is undefined
ERROR CONTEXT [object Object]

### What is expected?
The specified web page should work like in the latest version of Chrome
### What is actually happening?
In Internet Explorer and Edge there are errors that prevents to display the web page correctly.

---
### Additional comments
The web page should work on the latest version of modern browsers IE, Edge, FireFox and Chrome.

**Comment by ahmoba** [comment]
+1
I am having the same issue

**Comment by chelaruc** [comment]
@ionutafloarei @ahmoba this is a duplicate of #339. We will update the product soon with the correct code.

**Comment by ionutafloarei** [comment]
Hello @chelaruc  , we have a "Extend Premium Support" and we should have "Bug fixes in 24h during business days".  Can you please inform me when you will update the product with the correct core?

In bug #339 it is specified to "replace all the declare const $: any; with declare var $: any;". Since this is a an Angular Project, the files for replacement are in the node_modules and cannot be updated directly. Do you have another way around for this issue? Thanks.

**Comment by chelaruc** [comment]
Hi, @ionutafloarei.  Please search in the `src` folder for the wrong declaration and replace it with the correct one. Currently, we are working on another project and this one will be updated in February.

**Comment by ionutafloarei** [comment]
it is working in Edge, but not in IE. thanks for help. I am closing this issue.
