### ISSUE TITLE
[Bug] Seems to have a problem working with Microsoft Edge browser

### ISSUE THREAD

**Issue by dguinn-oncore** [creativetimofficial/ct-material-dashboard-pro-angular#368]
### Version
2.4.1
### Reproduction link
https://demos.creative-tim.com/material-dashboard-pro-angular2/#/dashboard
### Operating System
Windows 10
### Device
Desktop PC
### Browser & Version
Microsoft Edge (Legacy)
### Steps to reproduce
1. Go to the Creative Tim demo site with Microsoft Edge Legacy (not the chromium version...  basically older than 12/31/2019)
2. Verify that the sidebar and dashboard are not working, and that the console is reporting "ERROR ReferenceError: '$' is not defined" errors. 
### What is expected?
The template should work with the latest two versions of the Edge Browser
### What is actually happening?
The non-chromium version of MS edge is not working with the template.

---
### Solution
I think that this could be fixed with the correct "polyfills.ts" options, but I have no idea what those would be.
### Additional comments
It works perfectly in Chrome, and is a beautiful template that is well-packaged for very quick implementation.  Thank you!

**Comment by rarestoma** [comment]
Hi @dguinn-oncore,

Thank you for working with our products.

Please take a look at the solution described here: https://github.com/creativetimofficial/ct-material-dashboard-pro-angular/issues/339.

Thank you,
Rares

**Comment by dguinn-oncore** [comment]
Thank you Rares, that solution worked.  I thought I searched the issues, but I guess not very well (or maybe i searched the wrong repo...)

Thanks again, closing issue.
