### ISSUE TITLE
[Bug] Login form is hiden in the login page

### ISSUE THREAD

**Issue by ytaborda17** [creativetimofficial/ct-material-dashboard-pro-angular#372]
### Version
2.4.1
### Reproduction link
https://demos.creative-tim.com/material-dashboard-pro-angular2/#/pages/login
### Operating System
Ubuntu 18.04.4 LTS
### Device
Lenovo Ideapad 330S
### Browser & Version
Chrome Version 81.0.4044.138
### Steps to reproduce
Load the page
### What is expected?
To show the form from the start
### What is actually happening?
The form is hidden in the first load of the page, the user has to hit F5 to reload the page and then we can see the form.

---
### Additional comments
The first time that loads the animation doesn't occurs and the form remains hidden, I'm guessing the JS is not loading correctly, to show the form I have to hit F5 to reload the page, then it shows, please take a look into it.

**Comment by rarestoma** [comment]
Hi @ytaborda17,

Thank you for working with our products.

Please remove `.card-hidden` from `.card-login`'s div and now it should work fine.

I hope it helps.

All the best,
Rares

**Comment by ytaborda17** [comment]
It worked!

Sadly, I lose the animation.

Thanks any way.

**Comment by snooprogg** [comment]
If you change
const card = document.getElementsByClassName('card')[0]
to
const card = document.getElementById('card-hide-id');
in the login.component.ts file
and then add the id card-hide-id to card-hidden div in the login.component.html file, the animations will work

**Comment by ytaborda17** [comment]
Thanks, this fixed the initial issue.
