### ISSUE TITLE
[Bug] Circular Loader/Spinner

### ISSUE THREAD

**Issue by tariqbk** [creativetimofficial/ct-material-dashboard-pro-angular#373]
### Version
2.4.1
### Reproduction link
https://demos.creative-tim.com/material-dashboard-pro-angular2/#/dashboard
### Operating System
Windows 10
### Device
Desktop
### Browser & Version
Chrome Latest
### Steps to reproduce
There is no loader/spinner code in the template
### What is expected?
Click on forms, and a spinner should show while data is loading from the server.
### What is actually happening?
No Spinner Code

---
### Additional comments
Could you please point me to where this code is if its already available and how to use that spinner? Thanks!

**Comment by rarestoma** [comment]
Hi @tariqbk,

Thank you for working with our products.

Unfortunately, we don't provide spinner/loader on this template. 

Thank you,
Rares
