### ISSUE TITLE
The left "Moving" tab is not moving

### ISSUE THREAD

**Issue by donnytian** [creativetimofficial/ct-material-dashboard-pro-angular#76]
The "moving tab" in the left sidebar for active menu item actually is not moving during browser navigation. There is no "moving" animation at all.
Not sure if I am the only one have this issue, but I saw some calculations in code and suppose it should work.
In one case actually it will work, it's about navigate to an invalid path. The current view will not be replaced, the tab seems "moving" to the destination. But no luck for all other valid page routes.

**Comment by alexandru-paduraru** [comment]
@donnytian thank you for pointing that out. It was moving in the v1.2.0 and while removed the jQuery code, in our process of removing jQuery at all, we've got some issues and we decided to block that element till we have a stable code version with Angular Native properties. We are still investigating that and hopefully, we will add it back in the next v1.4.3 release :D 

Hope this information helps.

Best,
Alex
